---
engines:
  csslint:
    enabled: true
    checks:
      box-sizing:
        enabled: false
      fallback-colors:
        enabled: false
      important:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.css"
exclude_paths: []
