---
engines:
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths: []
